server:
  host: 0.0.0.0
  port: 8008

meta:
  title: i like git
  description: hey kid, come get your free software
  host: git.olexsmir.xyz

repo:
  dir: /home/olex/mugit-test/
  readmes:
    - README
    - README.md
    - readme
    - readme.md
    - readme.txt
  masters:
    - master
    - main
